Repository dbt-msft/dbt-sqlserver, pull requests merged in 2022-06, with the labels that each got.

#239 run CI tests on trusted PRs and include secrets
  .github/workflows/integration-tests-azure.yml
  .github/workflows/integration-tests-sqlserver.yml
Labels: safe to test

#248 Clean-up and update README
  README.md
  setup.py
Labels: chore

#249 update contribution docs and add Python 3.10
  .github/workflows/integration-tests-azure.yml
  .github/workflows/integration-tests-sqlserver.yml
  .github/workflows/unit-tests.yml
  CONTRIBUTING.md
  Makefile
  setup.py
  tox.ini
Labels: chore

#251 fix incremental unique array
  dbt/include/sqlserver/macros/materializations/models/incremental/merge.sql
  tests/functional/adapter/test_incremental.py
Labels: bugfix, safe to test

#214 Fix #213 - dbt test error when source name contains spaces and/or dots
  dbt/include/sqlserver/macros/adapters/indexes.sql
Labels: bugfix, safe to test
